### ISSUE TITLE
A sentence ending etc should have class="eoc"

### ISSUE THREAD

**Issue by robinwhittleton** [kifty/e-pauline-johnson_legends-of-vancouver#1]
https://github.com/kifty/e-pauline-johnson_legends-of-vancouver/blob/6141fa48b849b260c2fdd3cda9f8a294492b93c3/src/epub/text/endnotes.xhtml#L44

`<abbr>etc.</abbr>` should be `<abbr class="eoc">etc.</abbr>`.

**Comment by kifty** [comment]
Fixed in d142a61.
