### ISSUE TITLE
If no link, colophon names need a span

### ISSUE THREAD

**Issue by robinwhittleton** [kifty/e-pauline-johnson_legends-of-vancouver#2]
https://github.com/kifty/e-pauline-johnson_legends-of-vancouver/blob/6141fa48b849b260c2fdd3cda9f8a294492b93c3/src/epub/text/colophon.xhtml#L20

If you don’t want to link to a homepage then you’ll need to wrap your name in a `<span class="name">`. If you do have a homepage (or just your Github page?) then you can just link it with no class attribute (and add a link to content.opf).

**Comment by kifty** [comment]
Good idea about the Github page! Fixed in d142a61.
